---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordersdb-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ordersdb
    spec:
      containers:
      - name: ordersdb
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: ordersdb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: ordersdb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders-microservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: orders-microservice
    spec:
      containers:
      - name: orders-service
        image: registry.ng.bluemix.net/chrisking/us-micro-orders:jkwong-dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        env:
        - name: DB_IP
          value: ordersdb
---        
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    app: orders-microservice
...
