apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  labels:
    app: bluecompute
    tier: data
    micro: orders
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
    - port: {{ .Values.mysql.service.internalPort }}
      targetPort: {{ .Values.mysql.service.externalPort }}
  selector:
    app: bluecompute
    micro: orders
    tier: data
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
