# Default values for micro-orders.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ibmcase/bluecompute-orders
  pullPolicy: IfNotPresent
  tag: latest

hs256key:
  skipDelete: false
  secretName: hs256-key

mysql:
  dbname: ordersdb
  user: dbuser
  password: Pass4dbus3r
  service:
    name: ordersdb
    type: ClusterIP
    externalPort: 3306
    internalPort: 3306
  binding:
    name: binding-orders-mysql

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
